# Generated by Django 2.1.1 on 2018-09-27 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publish_date', models.DateField(default=datetime.datetime(2018, 9, 27, 19, 39, 19, 324163, tzinfo=utc))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Category')),
            ],
        ),
    ]
