# Generated by Django 2.1.1 on 2018-09-27 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 27, 19, 45, 46, 616649, tzinfo=utc)),
        ),
    ]
